"""initial_schema

Revision ID: ab923cd0b93a
Revises: 
Create Date: 2026-02-10 13:48:22.326184
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ab923cd0b93a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index('idx_user_teacher_id', 'users', ['teacher_id'], unique=False)
    op.create_table('words',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('english', sa.String(length=100), nullable=False),
    sa.Column('korean', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_word_english', 'words', ['english'], unique=False)
    op.create_index('idx_word_level', 'words', ['level'], unique=False)
    op.create_table('auth_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token')
    )
    op.create_index('idx_auth_token_user_id', 'auth_tokens', ['user_id'], unique=False)
    op.create_table('test_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('test_type', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('determined_level', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_test_completed_at', 'test_sessions', [sa.literal_column('completed_at DESC')], unique=False)
    op.create_index('idx_test_student_id', 'test_sessions', ['student_id'], unique=False)
    op.create_index('idx_test_type', 'test_sessions', ['test_type'], unique=False)
    op.create_table('test_answers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('test_session_id', sa.String(length=36), nullable=False),
    sa.Column('word_id', sa.String(length=36), nullable=False),
    sa.Column('selected_answer', sa.String(length=200), nullable=True),
    sa.Column('correct_answer', sa.String(length=200), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_order', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['test_session_id'], ['test_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_answer_is_correct', 'test_answers', ['is_correct'], unique=False)
    op.create_index('idx_answer_session_id', 'test_answers', ['test_session_id'], unique=False)
    op.create_index('idx_answer_word_id', 'test_answers', ['word_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_answer_word_id', table_name='test_answers')
    op.drop_index('idx_answer_session_id', table_name='test_answers')
    op.drop_index('idx_answer_is_correct', table_name='test_answers')
    op.drop_table('test_answers')
    op.drop_index('idx_test_type', table_name='test_sessions')
    op.drop_index('idx_test_student_id', table_name='test_sessions')
    op.drop_index('idx_test_completed_at', table_name='test_sessions')
    op.drop_table('test_sessions')
    op.drop_index('idx_auth_token_user_id', table_name='auth_tokens')
    op.drop_table('auth_tokens')
    op.drop_index('idx_word_level', table_name='words')
    op.drop_index('idx_word_english', table_name='words')
    op.drop_table('words')
    op.drop_index('idx_user_teacher_id', table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
